In [1]:
import numpy as np

In [5]:

a = np.array([1,2,3,4,6,5])
print(type(a))


<class 'numpy.ndarray'>


In [9]:

np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [13]:

a = np.array([1,2],dtype=float)
c = np.array([1,2],dtype=complex)


In [52]:

np.arange(1,11,3)


array([ 1,  4,  7, 10])

In [49]:

# product = no of ele present inside array
np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:

# for initilising 
np.ones((4,6))
np.zeros((4,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [61]:
np.random.random((3,4))*10

array([[3.53399283, 2.85311634, 2.4119767 , 1.15744722],
       [2.58567542, 3.30829643, 0.01198481, 3.45327768],
       [8.13083895, 7.65413399, 0.0300851 , 9.0015269 ]])

In [55]:

# equal distance pr points generate krta h with equal distance 
np.linspace(-10 , 10 , 10 , dtype=int)


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [51]:

np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:

a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [72]:

a1.ndim
a2.ndim
a3.ndim


(3, 4)

In [82]:

print(a1.size)
print(a2.size)
print(a3.size)
print()

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print()

print(a1.size)
print(a2.size)
print(a3.size)
print()




10
12
8

int32
float64
int32

10
12
8



In [85]:

# astype to reduce no like decrease age  
a2.astype(np.int32)


array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [87]:

a2.astype(np.int32) == 2


array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [94]:

a2[1][2]


6.0

In [96]:
a3[1,0,1]

5

In [97]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])